//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IPAddress { get; set; }
        public bool Status { get; set; }
        public System.DateTime Time { get; set; }
    }
}
